name: "Build"

on:
  push:
  workflow_dispatch:

jobs:
    notification:
      name: Notification
      runs-on: [ ubuntu-latest ]
      steps:
        - run: echo ${{ github.event_name }} ${{ github.ref_name }} 
