name: "Deploy"

on:
  workflow_run:
    workflows: [ "Build" ]
    branches: [ "update" ]
    types:
      - completed
  workflow_dispatch:

jobs:
    notification:
      name: Deployment
      runs-on: [ ubuntu-latest ]
      steps:
        - run: echo ${{ github.event_name }} ${{ github.ref_name }}
